# docker-compose.yml
# version: '3.8'

services:
  app:
    image: laravelsail/php83-composer:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MAILCOACH_APP_NAME=MyDripCampaign
      - MAILCOACH_APP_URL=http://localhost
      - MAILCOACH_ADMIN_EMAIL=admin@example.com
      - MAILCOACH_ADMIN_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mailcoach
      - DB_USERNAME=sail
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - MAILER_DSN=null
      # SMTP Settings - Configure below
      - MAILER_DSN=smtp://YOUR_SMTP_USER:YOUR_SMTP_PASSWORD@smtp.yourprovider.com:587?encryption=tls
    volumes:
      - ./app:/var/www/html
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mailcoach
      - MYSQL_USER=sail
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sail

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sail

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
    depends_on:
      - app

  horizon:
    image: laravelsail/php83-composer:latest
    working_dir: /var/www/html
    command: php /var/www/html/artisan horizon
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mailcoach
      - DB_USERNAME=sail
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
    volumes:
      - ./app:/var/www/html
    networks:
      - sail
    depends_on:
      - mysql
      - redis

networks:
  sail:
    driver: bridge

volumes:
  mysql_data: